# Form điền credentials cho Ads APIs
meta:
  app_id: "<meta_app_id>"
  app_secret: "<meta_app_secret>"
  access_token: "<meta_access_token>"

google_ads:
  developer_token: "<google_ads_developer_token>"
  client_id: "<google_oauth_client_id>"
  client_secret: "<google_oauth_client_secret>"
  refresh_token: "<google_oauth_refresh_token>"
  login_customer_id: "<google_ads_manager_id_optional>"

tiktok:
  access_token: "<tiktok_access_token>"
  advertiser_id: "<tiktok_advertiser_id_optional>"
